shopping_list = []
shopping_list.append('сүт')
shopping_list.append ('нан')
shopping_list.append ('алма')
shopping_list.append ('банан')
shopping_list.append ('киви')
print(shopping_list)
shopping_list.remove('нан')
print(shopping_list)
shopping_list.pop()
shopping_list.insert(0,'сабиз')
print(shopping_list)
print(shopping_list)
print(shopping_list[-3:])
print(shopping_list[::2])
print(shopping_list[1::2])
print(shopping_list[0])
print(shopping_list[3])
print(shopping_list[:3])
